# Open WebUI の AWS EKS向けカスタム設定
nameOverride: "open-webui"
namespaceOverride: "open-webui"

# デプロイメント設定
replicaCount: 1

# イメージ設定
image:
  repository: ghcr.io/open-webui/open-webui
  tag: "latest"
  pullPolicy: "Always"

# サービスアカウント設定
serviceAccount:
  create: true
  name: "open-webui"
  annotations: {}

# サービス設定 - AWS LoadBalancerを使用
service:
  type: LoadBalancer
  port: 8080
  targetPort: 8080
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"

# リソース設定
resources:
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 1Gi

# 永続化設定を無効化
persistence:
  enabled: false

# Pipelines設定
pipelines:
  enabled: true
  persistence:
    enabled: false
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 200m
      memory: 512Mi

# Open WebUI環境変数設定
extraEnvVars:
  - name: OPENAI_API_KEY
    value: "dummy-key"
  - name: OLLAMA_BASE_URL
    value: "http://open-webui-ollama:11434"
  - name: PORT
    value: "8080"

# Ollama設定
ollama:
  enabled: true
  fullnameOverride: "open-webui-ollama"
  service:
    type: ClusterIP
    port: 11434
  persistence:
    enabled: false
  resources:
    limits:
      cpu: 2000m
      memory: 4Gi
    requests:
      cpu: 1000m
      memory: 2Gi

# プローブ設定
livenessProbe:
  httpGet:
    path: /
    port: 8080
  initialDelaySeconds: 60
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /
    port: 8080
  initialDelaySeconds: 60
  periodSeconds: 10
