# Open WebUI の AWS EKS向けカスタム設定
nameOverride: "open-webui"
namespaceOverride: "open-webui"

# デプロイメント設定
replicaCount: 1

# イメージ設定
image:
  repository: ghcr.io/open-webui/open-webui
  tag: "latest"
  pullPolicy: "IfNotPresent"

# サービスアカウント設定
serviceAccount:
  enable: true
  name: "open-webui"
  annotations: {}
  automountServiceAccountToken: false

# サービス設定 - AWS LoadBalancerを使用
service:
  type: LoadBalancer
  port: 3000
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"

# Ingress設定 - AWS ALBを使用する場合は有効化
ingress:
  enabled: false
  className: "alb"
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
  hosts:
    - host: open-webui.example.com
      paths:
        - path: /
          pathType: Prefix
  tls: []

# リソース設定
resources:
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 1Gi

# Open WebUI環境変数設定
extraEnvVars:
  - name: OPENAI_API_KEY
    value: "dummy-key"
  - name: OLLAMA_BASE_URL
    value: "http://open-webui-ollama:11434"

# Ollama設定 - AWS EBS用の設定
ollama:
  enabled: true
  fullnameOverride: "open-webui-ollama"
  service:
    type: ClusterIP
    port: 11434
  persistence:
    enabled: true
    size: 20Gi
    storageClass: "gp3"  # AWSのEBSストレージクラス
  resources:
    limits:
      cpu: 2000m
      memory: 4Gi
    requests:
      cpu: 1000m
      memory: 2Gi
